FROM ubuntu:rolling AS ruby-builder

ENV TZ=Asia/Tokyo
ENV RUBY_VERSION=3.3.10
ENV RUBY_SHA256=b555baa467a306cfc8e6c6ed24d0d27b27e9a1bed1d91d95509859eac6b0e928

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get -y install \
    build-essential gcc g++ make libtool texinfo dpkg-dev pkg-config \
    libssl-dev zlib1g-dev libyaml-0-2 libyaml-dev wget libarchive-tools

RUN cd /tmp && \
    wget "https://cache.ruby-lang.org/pub/ruby/3.3/ruby-${RUBY_VERSION}.tar.gz" && \
    echo "${RUBY_SHA256}  ruby-${RUBY_VERSION}.tar.gz" | sha256sum --check && \
    bsdtar -zxf ruby-${RUBY_VERSION}.tar.gz && \
    cd ruby-${RUBY_VERSION} && \
    ./configure --prefix=/usr/local && \
    make install && \
    cd /tmp && \
    rm -rf ruby-${RUBY_VERSION}* && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

FROM ubuntu:rolling

ENV TZ=Asia/Tokyo
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

COPY --from=ruby-builder /usr/local /usr/local

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y upgrade && DEBIAN_FRONTEND=noninteractive apt-get -y install build-essential && DEBIAN_FRONTEND=noninteractive apt-get -y install tzdata

RUN DEBIAN_FRONTEND=noninteractive apt-get -y install wget \
    sed \
    net-tools \
    iputils-ping \
    traceroute \
    lsof \
    strace \
    man-db \
    tree \
    sysstat \
    pcp \
    vim \
    zsh \
    tcpdump \
    git \
    tmux \
    jq \
    htop \
    curl \
    bind9-dnsutils \
    postgresql \
    mysql-client \
    postgresql-client \
    redis \
    cowsay \
    libarchive-tools \
    libssl3t64 \
    zlib1g \
    libyaml-0-2

ENV GO_VERSION=1.24.11
RUN echo "GO_VERSION: $GO_VERSION" && \
    ARCH=$(arch) && \
    if [ "$ARCH" = "x86_64" ]; then \
        BUILDARCH="amd64"; \
    elif [ "$ARCH" = "aarch64" ]; then \
        BUILDARCH="arm64"; \
    elif [ "$ARCH" = "ppc64le" ]; then \
        BUILDARCH="ppc64le"; \
    elif [ "$ARCH" = "s390x" ]; then \
        BUILDARCH="s390x"; \
    else \
        echo "Unsupported architecture: $ARCH" && \
        exit 1; \
    fi && \
    wget https://go.dev/dl/go${GO_VERSION}.linux-${BUILDARCH}.tar.gz && \
    bsdtar -C /usr/local/src -zxf go${GO_VERSION}.linux-${BUILDARCH}.tar.gz && \
    ln -s /usr/local/src/go/bin/go /usr/local/bin/go && \
    rm go${GO_VERSION}.linux-${BUILDARCH}.tar.gz
