---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: uuid-api-replicaset
  namespace: doridoridoriand
spec:
  replicas: 3
  selector:
    matchLabels:
      labelName: uuid-api-label
  template:
    metadata:
      labels:
        app: uuid-api
        labelName: uuid-api-label
    spec:
      containers:
        - name: uuid-api-container
          image: doridoridoriand/uuid-api:0.0.1
          ports:
            - containerPort: 3000
