FROM openjdk:14

RUN cd /tmp && wget http://us.mirrors.quenda.co/apache//jmeter/binaries/apache-jmeter-5.3.tgz \
      && tar zxvf apache-jmeter-5.3.tgz \

CMD /bin/bash
#e.g. https://qiita.com/ma2shita/items/f1a68a3f909c5cee7869
